repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [ --config-file=.mypy.ini ]
        exclude: "tests/"
        additional_dependencies: [ 'strawberry-graphql', 'sqlalchemy-stubs' ]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
